# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_gcp_caip.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

'''
MANUAL EDIT!!!
Previous auto-generated import is:
    import grpc_service_pb2 as grpc__service__pb2
However, grpc_service_pb2 comes from tensorrtserver.api so the import fails.
'''
from tensorrtserver.api import grpc_service_pb2 as grpc__service__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc_gcp_caip.proto',
  package='nvidia.inferenceserver',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13grpc_gcp_caip.proto\x12\x16nvidia.inferenceserver\x1a\x12grpc_service.proto\"\xdb\x01\n\x0b\x43\x61ipRequest\x12\x39\n\x0crequest_type\x18\x01 \x01(\x0e\x32#.nvidia.inferenceserver.RequestType\x12=\n\x0estatus_request\x18\x02 \x01(\x0b\x32%.nvidia.inferenceserver.StatusRequest\x12;\n\rinfer_request\x18\x03 \x01(\x0b\x32$.nvidia.inferenceserver.InferRequest\x12\x15\n\rtrace_message\x18\x04 \x01(\t*a\n\x0bRequestType\x12\x10\n\x0cTYPE_UNKNOWN\x10\x00\x12\x17\n\x13TYPE_STATUS_REQUEST\x10\x01\x12\x16\n\x12TYPE_INFER_REQUEST\x10\x02\x12\x0f\n\x0bTYPE_TRACER\x10\x03\x62\x06proto3'
  ,
  dependencies=[grpc__service__pb2.DESCRIPTOR,])

_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='nvidia.inferenceserver.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TYPE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPE_STATUS_REQUEST', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPE_INFER_REQUEST', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPE_TRACER', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=289,
  serialized_end=386,
)
_sym_db.RegisterEnumDescriptor(_REQUESTTYPE)

RequestType = enum_type_wrapper.EnumTypeWrapper(_REQUESTTYPE)
TYPE_UNKNOWN = 0
TYPE_STATUS_REQUEST = 1
TYPE_INFER_REQUEST = 2
TYPE_TRACER = 3



_CAIPREQUEST = _descriptor.Descriptor(
  name='CaipRequest',
  full_name='nvidia.inferenceserver.CaipRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_type', full_name='nvidia.inferenceserver.CaipRequest.request_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status_request', full_name='nvidia.inferenceserver.CaipRequest.status_request', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='infer_request', full_name='nvidia.inferenceserver.CaipRequest.infer_request', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trace_message', full_name='nvidia.inferenceserver.CaipRequest.trace_message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=287,
)

_CAIPREQUEST.fields_by_name['request_type'].enum_type = _REQUESTTYPE
_CAIPREQUEST.fields_by_name['status_request'].message_type = grpc__service__pb2._STATUSREQUEST
_CAIPREQUEST.fields_by_name['infer_request'].message_type = grpc__service__pb2._INFERREQUEST
DESCRIPTOR.message_types_by_name['CaipRequest'] = _CAIPREQUEST
DESCRIPTOR.enum_types_by_name['RequestType'] = _REQUESTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CaipRequest = _reflection.GeneratedProtocolMessageType('CaipRequest', (_message.Message,), {
  'DESCRIPTOR' : _CAIPREQUEST,
  '__module__' : 'grpc_gcp_caip_pb2'
  # @@protoc_insertion_point(class_scope:nvidia.inferenceserver.CaipRequest)
  })
_sym_db.RegisterMessage(CaipRequest)


# @@protoc_insertion_point(module_scope)
